### ISSUE TITLE
Çalışan Tanımlama Güncelleme hk.

### ISSUE THREAD

**Issue by sametbegde** [feyzullahgezici72/Ihalematik#5]
Kuzen mesela griddeki 5. satırdaki bir çalışanı güncellediğimde ve güncelleme formu kapandığında
güncellenen satır seçili kalsın.. 
güncelleme işi bittiğinde hangi satırın güncellendiği belli olmuyor

**Comment by feyzullahgezici72** [comment]
halledildi
